name: 'Zenn X Post Action'
description: 'Automatically post Zenn articles to X (Twitter) with AI-generated lead text'

inputs:
  openai_api_key:
    description: 'OpenAI API Key'
    required: true
  twitter_api_key:
    description: 'Twitter API Key'
    required: true
  twitter_api_secret:
    description: 'Twitter API Secret'
    required: true
  twitter_access_token:
    description: 'Twitter Access Token'
    required: true
  twitter_access_secret:
    description: 'Twitter Access Secret'
    required: true
  new_files:
    description: 'Newly added markdown files'
    required: false
  modified_files:
    description: 'Modified markdown files'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check for new published articles
      id: article-check
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/check-articles.sh"
        "${{ github.action_path }}/scripts/check-articles.sh" "${{ inputs.new_files }}" "${{ inputs.modified_files }}"
      
    # ä»¥ä¸‹ ãƒªãƒ¼ãƒ‰åˆ†ç”Ÿæˆ + Postæ–‡ç”Ÿæˆ

    - name: Generate AI Lead Text
      if: steps.article-check.outputs.should_post == 'true'
      id: generate-lead
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/generate-ai-lead.sh"
        "${{ github.action_path }}/scripts/generate-ai-lead.sh" "${{ steps.article-check.outputs.article_url }}" "${{ inputs.openai_api_key }}"

    - name: Create Final Message
      if: steps.article-check.outputs.should_post == 'true'
      id: create-message
      shell: bash
      run: |
        AI_LEAD="${{ steps.generate-lead.outputs.ai_lead_text }}"
        TITLE="${{ steps.article-check.outputs.article_title }}"
        URL="${{ steps.article-check.outputs.article_url }}"
        POST_MESSAGE="ðŸ“ æ–°ã—ã„æŠ€è¡“è¨˜äº‹ã‚’æŠ•ç¨¿ã—ã¾ã—ãŸï¼\n\n${AI_LEAD}\n\n${URL}"
        echo "post_message=${POST_MESSAGE}" >> $GITHUB_OUTPUT
        echo "Post Message created:"
        printf "%s" "$POST_MESSAGE"

    # ä»¥ä¸‹ X Post

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: |
        pip install requests requests-oauthlib

    - name: Post to X (Twitter)
      if: steps.article-check.outputs.should_post == 'true'
      shell: bash
      run: |
        python "${{ github.action_path }}/scripts/tweet.py"
      env:
        MESSAGE: ${{ steps.create-message.outputs.post_message }}
        TWITTER_API_KEY: ${{ inputs.twitter_api_key }}
        TWITTER_API_SECRET: ${{ inputs.twitter_api_secret }}
        TWITTER_ACCESS_TOKEN: ${{ inputs.twitter_access_token }}
        TWITTER_ACCESS_SECRET: ${{ inputs.twitter_access_secret }} 