name: 'Zenn X Post Action'
description: 'Automatically post Zenn articles to X (Twitter) with AI-generated lead text'

inputs:
  openai_api_key:
    description: 'OpenAI API Key (空の場合はAIリード文生成をスキップ)'
    required: false
  x_api_key:
    description: 'X API Key'
    required: true
  x_api_secret:
    description: 'X API Secret'
    required: true
  x_access_token:
    description: 'X Access Token'
    required: true
  x_access_secret:
    description: 'X Access Secret'
    required: true
  new_files:
    description: 'Newly added markdown files'
    required: false
  modified_files:
    description: 'Modified markdown files'
    required: false
  zenn_user_id:
    description: 'Zenn User ID'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: |
        pip install requests requests-oauthlib

    # 以下 差分チェック

    - name: Check for new published articles
      id: article-check
      shell: bash
      run: |
        python "${{ github.action_path }}/scripts/check-articles.py" "${{ inputs.new_files }}" "${{ inputs.modified_files }}"
      env:
        ZENN_USER_ID: ${{ inputs.zenn_user_id }}
      
    # 以下 リード分生成 + Post文生成

    - name: Generate AI Lead Text
      if: steps.article-check.outputs.should_post == 'true'
      id: generate-lead
      shell: bash
      run: |
        python "${{ github.action_path }}/scripts/generate-ai-lead.py" "${{ steps.article-check.outputs.article_title }}" "${{ steps.article-check.outputs.article_url }}" "${{ inputs.openai_api_key }}"

    # 以下 X Post

    - name: Post to X
      if: steps.article-check.outputs.should_post == 'true'
      shell: bash
      run: |
        python "${{ github.action_path }}/scripts/tweet.py"
      env:
        MESSAGE: ${{ steps.generate-lead.outputs.post_message }}
        X_API_KEY: ${{ inputs.x_api_key }}
        X_API_SECRET: ${{ inputs.x_api_secret }}
        X_ACCESS_TOKEN: ${{ inputs.x_access_token }}
        X_ACCESS_SECRET: ${{ inputs.x_access_secret }} 