name: 'Zenn X Post Action'
description: 'Automatically post Zenn articles to X (Twitter) with AI-generated lead text'

inputs:
  openai_api_key:
    description: 'OpenAI API Key (ç©ºã®å ´åˆã¯AIãƒªãƒ¼ãƒ‰æ–‡ç”Ÿæˆã‚’ã‚¹ã‚­ãƒƒãƒ—)'
    required: false
  x_api_key:
    description: 'X API Key'
    required: true
  x_api_secret:
    description: 'X API Secret'
    required: true
  x_access_token:
    description: 'X Access Token'
    required: true
  x_access_secret:
    description: 'X Access Secret'
    required: true
  new_files:
    description: 'Newly added markdown files'
    required: false
  modified_files:
    description: 'Modified markdown files'
    required: false
  zenn_user_id:
    description: 'Zenn User ID'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: |
        pip install requests requests-oauthlib

    # ä»¥ä¸‹ å·®åˆ†ãƒã‚§ãƒƒã‚¯

    - name: Check for new published articles
      id: article-check
      shell: bash
      run: |
        python "${{ github.action_path }}/scripts/check-articles.py" "${{ inputs.new_files }}" "${{ inputs.modified_files }}"
      env:
        ZENN_USER_ID: ${{ inputs.zenn_user_id }}
      
    # ä»¥ä¸‹ ãƒªãƒ¼ãƒ‰åˆ†ç”Ÿæˆ + Postæ–‡ç”Ÿæˆ

    - name: Generate AI Lead Text
      if: steps.article-check.outputs.should_post == 'true'
      id: generate-lead
      shell: bash
      run: |
        python "${{ github.action_path }}/scripts/generate-ai-lead.py" "${{ steps.article-check.outputs.article_url }}" "${{ inputs.openai_api_key }}"

    - name: Create Final Message
      if: steps.article-check.outputs.should_post == 'true'
      id: create-message
      shell: bash
      run: |
        AI_LEAD="${{ steps.generate-lead.outputs.ai_lead_text }}"
        TITLE="${{ steps.article-check.outputs.article_title }}"
        URL="${{ steps.article-check.outputs.article_url }}"
        POST_MESSAGE="ðŸ“ æ–°ã—ã„æŠ€è¡“è¨˜äº‹ã‚’æŠ•ç¨¿ã—ã¾ã—ãŸï¼\n\n${AI_LEAD}\n\n${URL}"
        echo "post_message=${POST_MESSAGE}" >> $GITHUB_OUTPUT
        echo "Post Message created:"
        printf "%s" "$POST_MESSAGE"

    # ä»¥ä¸‹ X Post

    - name: Post to X
      if: steps.article-check.outputs.should_post == 'true'
      shell: bash
      run: |
        python "${{ github.action_path }}/scripts/tweet.py"
      env:
        MESSAGE: ${{ steps.create-message.outputs.post_message }}
        X_API_KEY: ${{ inputs.x_api_key }}
        X_API_SECRET: ${{ inputs.x_api_secret }}
        X_ACCESS_TOKEN: ${{ inputs.x_access_token }}
        X_ACCESS_SECRET: ${{ inputs.x_access_secret }} 